### PR TITLE
Add argument '-s' to skip the menu when the script runs on Travis CI

### PR DESCRIPTION
**Pull request by raduiman**
I've changed the .travis.yml file, by adding '-s' argument for skipping the main-menu when the script runs on Travis CI

FIC-Travis

### CODE REVIEW

**Comment by Archaeopteryx** [comment]
@lundjordan Can you merge that, please? The job fails to run successfully and https://github.com/mozilla-releng/firefox-infra-changelog/blob/master/changelog.md misses (new) data.

**Comment by Akhliskun** [comment]
If we get our github accounts rights for merge, I can get this stuff fixed :)

**Comment by lundjordan** [comment]
> If we get our github accounts rights for merge, I can get this stuff fixed :)

@Akhliskun - That's awesome! I added you and Radu individually with `write` access. Is there anyone else that would be interested in contributing?

**Comment by bccrisan** [comment]
> 
> 
> > If we get our github accounts rights for merge, I can get this stuff fixed :)
> 
> @Akhliskun - That's awesome! I added you and Radu individually with `write` access. Is there anyone else that would be interested in contributing?

Count me in! ✌✔

**Comment by lundjordan** [comment]
> Count me in! ✌✔

Welcome (back)!

**Comment by Archaeopteryx** [comment]
Does this need a manual deploy?

**Comment by Akhliskun** [comment]
I believe a re-deploy on BDTools server is needed (or check the cron for it) but also (if I'm not wrong) CiDuty's github account needs to be given write access back to the repo.

**Comment by lundjordan** [comment]
> I believe a re-deploy on BDTools server is needed (or check the cron for it) but also (if I'm not wrong) CiDuty's github account needs to be given write access back to the repo.

I re-added ciduty bot. I removed it because I wasn't included as a recipient in the private repo where we keep its creds and ssh key. So I deleted that file from private repo and revoked all of Cidutybot's permissions in github.

Do those exist somewhere? Could they be sent to me encrypted? Here's my gpg key: https://gpg.mozilla.org/pks/lookup?search=jlund%40mozilla.com&op=vindex

Failing that, I could create a new bot account and share those creds with someone who has access to BDTools server.

@Akhliskun thoughts?

**Comment by Akhliskun** [comment]
@lundjordan I'm pretty sure I signed the file with the buildduty.txt file :o If your GPG is not there, that explains why your key wasn't added (tho I remember I verified and everything was good). 

I see 2 possible paths:
- Revert the file deletion, send it to me and I'm decrypt and re-encrypt it with your gpg.
- Will look to see if I still have the credentials.

Will come back in a few hours.

**Comment by lundjordan** [comment]
> Revert the file deletion, send it to me and I'm decrypt and re-encrypt it with your gpg.

done. sent to the SV email I had in contacts.

**Comment by lundjordan** [comment]
danut was able to recover it himself.

**Comment by lundjordan** [comment]
okay, so ciduty should have `write` access in this repo, what's next?

**Comment by raduiman** [comment]
we used a crontask on buiduty-tools server. It was created by @Akhliskun manually. I suppose that a re-deploy on the server is needed and then change the cron to run the following command:
> python client.py -s -a -p

-s -> to skip the mainmenu
-a -> to run the script for all the repsitories
-p -> to auto add, commit and push the /data files

**Comment by Akhliskun** [comment]
What tadu said should do it. 
Of not, I can handle this with mtabara amd guide him stept by step (or at least explain everything that he needs to do) as I know he has access to BDTools server + hes on our timezone.

**Pull request merged**
